version: '3'
services:
  #don't need env container because static code upload
  # environment:
  #   hostname: environment
  #   env_file:
  #     - docker/environment/docker.env
  #   build:
  #     context: ./
  #     dockerfile: docker/environment/Dockerfile
  #   ports:
  #     - '8085:8085'

  agent:
    hostname: agent
    env_file:
      - docker/agent/docker.env
    build:
      context: ./
      dockerfile: docker/agent/Dockerfile
